name: Daily build

# Controls when the action will run.
on: 
  schedule:
    - cron: '30 2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Build the ballerina project
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack ./peoplehr

            # Test the ballerina project
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      test --test-report --code-coverage --coverage-format=xml ./peoplehr
              env:
                BASE_URL: ${{ secrets.BASE_URL }}
                API_KEY: ${{ secrets.API_KEY }}
                EMAIL_ADDRESS: ${{ secrets.emailAddress }}
                PASSWORD: ${{ secrets.PASSWORD }}
                QUERY_NAME: ${{ secrets.QUERY_NAME }}

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
                
